"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, ClipboardList, HeartPulse, RefreshCw, ShieldCheck } from "lucide-react";
import { requestApi } from "../../lib/api-client";

type Row = Record<string, unknown>;
type Organ = { id: string; reference: string; organType: string; bloodGroup?: string | null; status: string; preservationStartTime?: string | null; preservation?: Row; donor?: { reference: string }; currentLocation?: { name: string }; destinationCentre?: { name: string }; offers?: Array<{ status: string }> };
type Resource = "organs" | "donors" | "recipients" | "offers" | "procurements" | "audit";
const nav = [{ href: "/organ-centre", label: "Overview" }, { href: "/organ-centre/organs", label: "Organs" }, { href: "/organ-centre/donors", label: "Donors" }, { href: "/organ-centre/recipients", label: "Recipients" }, { href: "/organ-centre/matching", label: "Matching" }, { href: "/organ-centre/offers", label: "Offers" }, { href: "/organ-centre/procurement", label: "Procurement" }, { href: "/organ-centre/audit", label: "Audit" }];
const titles: Record<Resource, { heading: string; description: string; key: string }> = {
	organs: { heading: "Organ inventory", description: "Track organ coordination records and their current workflow state.", key: "organs" },
	donors: { heading: "Donor records", description: "Review donor references and consent authorization status.", key: "donors" },
	recipients: { heading: "Recipient requirements", description: "View active, structured requirements for coordination searches.", key: "recipients" },
	offers: { heading: "Organ offers", description: "Track offers and response deadlines across your centre.", key: "offers" },
	procurements: { heading: "Procurement", description: "Track scheduled procurement and retrieval workflow records.", key: "procurements" },
	audit: { heading: "Organ audit history", description: "Review recorded operational events within your authorized centre scope.", key: "events" },
};

export function OrganOverview() {
	const [organs, setOrgans] = useState<Organ[]>([]);
	const [offerCount, setOfferCount] = useState(0);
	const [error, setError] = useState("");
	const [loading, setLoading] = useState(true);
	const refresh = () => { setLoading(true); setError(""); void Promise.all([requestApi<{ organs: Organ[] }>("/api/organs"), requestApi<{ offers: Row[] }>("/api/organs/offers")]).then(([organData, offerData]) => { setOrgans(organData.organs); setOfferCount(offerData.offers.filter((offer) => ["SENT", "UNDER_REVIEW"].includes(String(offer.status))).length); }).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)); };
	useEffect(refresh, []);
	const counts = useMemo(() => ({ active: organs.filter((organ) => !["COMPLETED", "CANCELLED", "DISCARDED", "EXPIRED", "UNAVAILABLE"].includes(organ.status)).length, available: organs.filter((organ) => organ.status === "AVAILABLE").length, procurement: organs.filter((organ) => ["RETRIEVAL_SCHEDULED", "RETRIEVAL_IN_PROGRESS"].includes(organ.status)).length, critical: organs.filter((organ) => ["CRITICAL", "EXPIRED"].includes(String(organ.preservation?.status))).length, completed: organs.filter((organ) => organ.status === "COMPLETED" || organ.status === "TRANSPLANTED").length }), [organs]);
	return <main className="page-stack organ-workspace">
		<header className="page-heading"><div><span className="eyebrow">ORGAN COORDINATION</span><h1>Coordination overview</h1><p>Operational workflow status for your authorized organ centre.</p></div><button className="button" onClick={refresh}><RefreshCw size={14}/> Refresh</button></header>
		<nav className="organ-nav">{nav.map((item) => <Link href={item.href} key={item.href}>{item.label}<ArrowRight size={13}/></Link>)}</nav>
		{error && <div role="alert" className="error">{error}</div>}
		{loading ? <section className="panel">Loading authorized organ records…</section> : <>
			<div className="metric-grid organ-metrics">
				<Metric icon={<HeartPulse/>} label="ACTIVE ORGANS" value={counts.active} note="Authorized workflow records"/>
				<Metric icon={<ShieldCheck/>} label="AVAILABLE" value={counts.available} note="Awaiting coordination"/>
				<Metric icon={<ClipboardList/>} label="IN PROCUREMENT" value={counts.procurement} note="Scheduled or in progress"/>
				
				<Metric icon={<HeartPulse/>} label="ACTIVE OFFERS" value={offerCount} note="Awaiting centre response"/>
				<Metric icon={<ShieldCheck/>} label="CRITICAL TIMERS" value={counts.critical} note="Configured operational thresholds"/>
				<Metric icon={<ClipboardList/>} label="COMPLETED" value={counts.completed} note="Recorded outcomes"/>
			</div>
			<section className="panel"><div className="panel-heading"><div><span className="eyebrow">RECENT RECORDS</span><h2>Organ coordination</h2></div><Link className="button small" href="/organ-centre/organs">View inventory</Link></div>
				{organs.length === 0 ? <div className="empty-state"><span className="empty-icon"><HeartPulse/></span><h3>No organ records yet</h3><p>Authorized organ-centre records will appear here.</p></div> : <OrganTable organs={organs.slice(0, 8)}/>}
			</section>
			<p className="organ-disclaimer">LifeLink provides operational coordination information. Final medical eligibility, acceptance, and allocation decisions remain with authorized professionals and applicable authorities.</p>
		</>}
	</main>;
}

export function OrganResourcePage({ resource, matching = false }: { resource: Resource; matching?: boolean }) {
	const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [matches, setMatches] = useState<Row[]>([]); const config = titles[resource];
	const reload = () => { setLoading(true); const endpoint = resource; void requestApi<Record<string, Row[]>>(`/api/organs/${endpoint}`).then((data) => setRows(data[config.key] ?? [])).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)); };
	useEffect(reload, [resource, config.key]);
	const respond = async (offerId: string, action: "ACCEPT" | "REJECT") => { setError(""); try { await requestApi(`/api/organs/offers/${offerId}/respond`, { method: "POST", body: JSON.stringify({ action }) }); reload(); } catch (e) { setError((e as Error).message); } };
	const generateMatches = async (organId: string) => { setError(""); try { const result = await requestApi<{ matches: Row[] }>(`/api/organs/${organId}/matches`, { method: "POST", body: JSON.stringify({}) }); setMatches(result.matches); } catch (e) { setError((e as Error).message); } };
	const reviewMatch = async (matchId: string) => { try { await requestApi(`/api/organs/matches/${matchId}/review`, { method: "PATCH", body: JSON.stringify({ status: "SHORTLISTED" }) }); const match = matches.find((item) => item.id === matchId); if (match) setMatches((current) => current.map((item) => item.id === matchId ? { ...item, status: "SHORTLISTED" } : item)); } catch (e) { setError((e as Error).message); } };
	const createOffer = async (matchId: string) => { try { await requestApi("/api/organs/offers", { method: "POST", body: JSON.stringify({ matchId, responseDeadline: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString() }) }); setMatches((current) => current.filter((match) => match.id !== matchId)); reload(); } catch (e) { setError((e as Error).message); } };
	const advanceStatus = async (id: string, status: string) => { const endpoint = `/api/organs/procurements/${id}/status`; try { await requestApi(endpoint, { method: "PATCH", body: JSON.stringify({ status }) }); reload(); } catch (e) { setError((e as Error).message); } };
	return <main className="page-stack organ-workspace"><header className="page-heading"><div><span className="eyebrow">ORGAN COORDINATION</span><h1>{matching ? "Potential coordination matching" : config.heading}</h1><p>{matching ? "Generate transparent candidates from active requirements for authorized review." : config.description}</p></div><Link href="/organ-centre" className="button">Overview</Link></header><nav className="organ-nav">{nav.map((item) => <Link href={item.href} key={item.href}>{item.label}<ArrowRight size={13}/></Link>)}</nav>{error && <div className="error" role="alert">{error}</div>}<OrganCreateForm resource={resource} onCreated={reload} onError={setError}/>{loading ? <section className="panel">Loading authorized records…</section> : rows.length === 0 ? <section className="panel empty-state"><span className="empty-icon"><ClipboardList/></span><h3>No records to display</h3><p>Records visible to your account will appear here.</p></section> : <section className="panel">{resource === "organs" ? <OrganTable organs={rows as unknown as Organ[]} onGenerateMatches={generateMatches}/> : <ResourceTable rows={rows} resource={resource} onOfferResponse={respond} onAdvance={advanceStatus}/>}</section>}{matches.length > 0 && <section className="panel"><span className="eyebrow">POTENTIAL COORDINATION MATCHES</span><h2>Ranked candidates</h2><CandidateTable matches={matches} onShortlist={reviewMatch} onOffer={createOffer}/><p className="organ-disclaimer">These candidates are ranked using configured coordination filters. This is not clinical compatibility or an allocation decision.</p></section>}</main>;
}

function OrganCreateForm({ resource, onCreated, onError }: { resource: Resource; onCreated: () => void; onError: (message: string) => void }) {
	const [values, setValues] = useState<Record<string, string>>({}); const [options, setOptions] = useState<Row[]>([]); const [organOptions, setOrganOptions] = useState<Row[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
	const needsOrgans = resource === "procurements";
	useEffect(() => { const endpoint = resource === "organs" ? "/api/organs/donors" : needsOrgans ? "/api/organs" : ""; if (!endpoint) return; void requestApi<Record<string, Row[]>>(endpoint).then((data) => setOptions(data.donors ?? data.institutions ?? [] )).catch((error: Error) => onError(error.message)); if (needsOrgans) void requestApi<{ organs: Row[] }>("/api/organs").then((data) => setOrganOptions(data.organs)).catch((error: Error) => onError(error.message)); }, [resource, needsOrgans, onError]);
	const set = (key: string, value: string) => setValues((current) => ({ ...current, [key]: value }));
	if (!["donors", "recipients", "organs", "procurements"].includes(resource)) return null;
	const labels: Record<string, string> = { donors: "Register donor", recipients: "Add recipient requirement", organs: "Register organ record", procurements: "Schedule procurement" };
	const submit = async (event: React.FormEvent<HTMLFormElement>) => {
		event.preventDefault(); setBusy(true); setMessage(""); onError("");
		const urls: Record<string, string> = { donors: "/api/organs/donors", recipients: "/api/organs/recipients", organs: "/api/organs", procurements: "/api/organs/procurements" };
		const body: Record<string, unknown> = { ...values };
		if (resource === "organs" || resource === "recipients") { if (body.bloodGroup === "") delete body.bloodGroup; if (body.priority) body.priority = String(body.priority).toUpperCase(); }
		if (["procurements", "recipients"].includes(resource)) { if (body.scheduledAt) body.scheduledAt = new Date(String(body.scheduledAt)).toISOString(); if (body.requiredBy) body.requiredBy = new Date(String(body.requiredBy)).toISOString(); for (const key of ["latitude", "longitude", "maximumDistanceKm"]) { if (body[key] === "") delete body[key]; else if (body[key] !== undefined) body[key] = Number(body[key]); } }
		try { await requestApi(urls[resource], { method: "POST", body: JSON.stringify(body) }); setValues({}); setMessage("Record created."); onCreated(); } catch (error) { onError((error as Error).message); } finally { setBusy(false); }
	};
	const field = (name: string, label: string, required = false, type = "text") => <label key={name}>{label}<input required={required} type={type} value={values[name] ?? ""} onChange={(event) => set(name, event.target.value)}/></label>;
	const select = (name: string, label: string, choices: string[], required = true) => <label key={name}>{label}<select required={required} value={values[name] ?? ""} onChange={(event) => set(name, event.target.value)}><option value="">Select…</option>{choices.map((choice) => <option key={choice} value={choice.split("|")[0]}>{(choice.split("|")[1] ?? choice).replaceAll("_", " ")}</option>)}</select></label>;
	return <form className="panel organ-create-form" onSubmit={(event) => void submit(event)}><div><span className="eyebrow">WORKFLOW ACTION</span><h2>{labels[resource]}</h2></div><div className="organ-create-fields">
		{resource === "donors" && <>{field("donorType", "Donor type", true)}{field("consentType", "Consent type", true)}{select("bloodGroup", "Blood group", ["A_POSITIVE", "A_NEGATIVE", "B_POSITIVE", "B_NEGATIVE", "AB_POSITIVE", "AB_NEGATIVE", "O_POSITIVE", "O_NEGATIVE"], false)}{field("documentReference", "Document reference")}</>}
		{resource === "recipients" && <>{select("organType", "Organ / tissue", ["KIDNEY", "LIVER", "HEART", "LUNG", "PANCREAS", "INTESTINE", "CORNEA", "BONE_MARROW", "OTHER"])}{select("bloodGroup", "Blood group", ["A_POSITIVE", "A_NEGATIVE", "B_POSITIVE", "B_NEGATIVE", "AB_POSITIVE", "AB_NEGATIVE", "O_POSITIVE", "O_NEGATIVE"], false)}{select("priority", "Coordination priority", ["NORMAL", "URGENT", "EMERGENCY"])}{field("maximumDistanceKm", "Maximum search distance (km)", false, "number")}{field("latitude", "Requirement latitude", false, "number")}{field("longitude", "Requirement longitude", false, "number")}{field("requiredBy", "Required by", false, "datetime-local")}</>}
		{resource === "organs" && <>{select("donorId", "Donor reference", options.map((row) => `${String(row.id)}|${String(row.reference)}`))}{select("organType", "Organ / tissue", ["KIDNEY", "LIVER", "HEART", "LUNG", "PANCREAS", "INTESTINE", "CORNEA", "BONE_MARROW", "OTHER"])}{select("bloodGroup", "Blood group", ["A_POSITIVE", "A_NEGATIVE", "B_POSITIVE", "B_NEGATIVE", "AB_POSITIVE", "AB_NEGATIVE", "O_POSITIVE", "O_NEGATIVE"], false)}</>}
		{resource === "procurements" && <>{select("organId", "Organ reference", organOptions.map((row) => `${String(row.id)}|${String(row.reference)}`))}{field("scheduledAt", "Scheduled time", true, "datetime-local")}{field("responsibleReference", "Responsible professional reference")}</>}
	</div><div className="organ-form-footer">{message && <small>{message}</small>}<button className="button primary" disabled={busy}>{busy ? "Saving…" : labels[resource]}</button></div></form>;
}

export function OrganDetailPage({ id }: { id: string }) {
	const [organ, setOrgan] = useState<Row | null>(null); const [error, setError] = useState("");
	const [busy, setBusy] = useState(false); const [nextStatus, setNextStatus] = useState(""); const [method, setMethod] = useState("STATIC_COLD_STORAGE");
	const load = () => { void requestApi<Row>(`/api/organs/${id}`).then(setOrgan).catch((e: Error) => setError(e.message)); };
	useEffect(load, [id]);
	const transitions: Record<string, string[]> = { REGISTERED: ["ASSESSMENT_PENDING", "CANCELLED"], ASSESSMENT_PENDING: ["ELIGIBLE_FOR_COORDINATION", "UNAVAILABLE"], ELIGIBLE_FOR_COORDINATION: ["AVAILABLE", "UNAVAILABLE"], AVAILABLE: ["MATCHING", "UNAVAILABLE", "CANCELLED"], MATCHING: ["OFFERED", "AVAILABLE", "UNAVAILABLE"], OFFERED: ["ACCEPTED", "AVAILABLE", "EXPIRED", "CANCELLED"], ACCEPTED: ["RETRIEVAL_SCHEDULED", "CANCELLED"], RETRIEVAL_SCHEDULED: ["RETRIEVAL_IN_PROGRESS", "CANCELLED"], RETRIEVAL_IN_PROGRESS: ["RETRIEVED", "CANCELLED", "UNAVAILABLE"], RETRIEVED: ["PRESERVING"], PRESERVING: ["IN_TRANSIT", "UNAVAILABLE", "EXPIRED"], IN_TRANSIT: ["ARRIVED", "EXPIRED"], ARRIVED: ["FINAL_ASSESSMENT"], FINAL_ASSESSMENT: ["ALLOCATED", "UNAVAILABLE"], ALLOCATED: ["TRANSPLANTED"], TRANSPLANTED: ["COMPLETED"] };
	const advance = async () => { if (!nextStatus) return; setBusy(true); try { await requestApi(`/api/organs/${id}/status`, { method: "PATCH", body: JSON.stringify({ status: nextStatus }) }); setNextStatus(""); load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
	const startPreservation = async () => { setBusy(true); try { await requestApi(`/api/organs/${id}/preservation/start`, { method: "POST", body: JSON.stringify({ method }) }); load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
	return <main className="page-stack organ-workspace"><header className="page-heading"><div><span className="eyebrow">ORGAN COORDINATION / DETAIL</span><h1>{String(organ?.reference ?? "Organ record")}</h1><p>Protected operational record and workflow history.</p></div><Link href="/organ-centre/organs" className="button">Back to inventory</Link></header>{error && <div className="error" role="alert">{error}</div>}{!organ && !error ? <section className="panel">Loading record…</section> : organ ? <><section className="panel organ-detail-grid">{["organType", "status", "bloodGroup", "currentLocation", "destinationCentre", "preservationMethod", "preservationStartTime"].map((key) => <div key={key}><small>{key.replaceAll(/([A-Z])/g, " $1").toUpperCase()}</small><strong>{nestedValue(organ, key)}</strong></div>)}</section>{(transitions[String(organ.status)]?.length ?? 0) > 0 && <section className="panel organ-status-action"><span className="eyebrow">AUTHORIZED WORKFLOW TRANSITION</span><div><select value={nextStatus} onChange={(event) => setNextStatus(event.target.value)}><option value="">Select next state…</option>{(transitions[String(organ.status)] ?? []).map((status) => <option key={status}>{status}</option>)}</select><button className="button primary" disabled={busy || !nextStatus} onClick={() => void advance()}>Update status</button></div></section>}{organ.status === "RETRIEVED" && <section className="panel organ-status-action"><span className="eyebrow">PRESERVATION RECORD</span><div><select value={method} onChange={(event) => setMethod(event.target.value)}>{["STATIC_COLD_STORAGE", "HYPOTHERMIC_MACHINE_PERFUSION", "NORMOTHERMIC_MACHINE_PERFUSION", "CORNEAL_STORAGE_MEDIUM", "OTHER"].map((value) => <option key={value}>{value}</option>)}</select><button className="button primary" disabled={busy} onClick={() => void startPreservation()}>Start coordination preservation timer</button></div><small>Operational timing only; this does not determine clinical viability.</small></section>}<section className="panel"><span className="eyebrow">WORKFLOW HISTORY</span><h2>Recorded events</h2><ResourceTable rows={(organ.events as Row[] | undefined) ?? []} resource="organs"/></section><p className="organ-disclaimer">Operational timing information does not establish clinical suitability.</p></> : null}</main>;
}

export function OrganRelatedDetailPage({ id, resource }: { id: string; resource: "donors" | "recipients" | "offers" }) {
	const [record, setRecord] = useState<Row | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
	const load = () => { setError(""); void requestApi<Row>(`/api/organs/${resource}/${id}`).then(setRecord).catch((e: Error) => setError(e.message)); };
	useEffect(load, [id, resource]);
	const verifyConsent = async () => { setBusy(true); try { await requestApi(`/api/organs/donors/${id}/consent/verify`, { method: "POST" }); load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
	const heading = resource === "donors" ? "Donor record" : resource === "recipients" ? "Recipient requirement" : "Organ offer";
	const reference = String(record?.reference ?? heading);
	const groups = ["consents", "organs", "requirement", "matches", "offers", "events"];
	return <main className="page-stack organ-workspace"><header className="page-heading"><div><span className="eyebrow">ORGAN COORDINATION / DETAIL</span><h1>{reference}</h1><p>{heading} · protected operational data.</p></div><Link href={`/organ-centre/${resource}`} className="button">Back to list</Link></header>{error && <div className="error" role="alert">{error}</div>}{!record && !error ? <section className="panel">Loading authorized record…</section> : record ? <><section className="panel organ-detail-grid">{Object.entries(record).filter(([key, value]) => !groups.includes(key) && value !== null && typeof value !== "object" && key !== "id").map(([key, value]) => <div key={key}><small>{key.replaceAll(/([A-Z])/g, " $1").toUpperCase()}</small><strong>{displayValue(value)}</strong></div>)}</section>{resource === "donors" && record.consentStatus === "RECORDED" && <button className="button primary" disabled={busy} onClick={() => void verifyConsent()}>{busy ? "Verifying…" : "Verify recorded consent"}</button>}{groups.filter((key) => record[key] !== undefined).map((key) => <section className="panel" key={key}><span className="eyebrow">{key.replaceAll(/([A-Z])/g, " $1").toUpperCase()}</span>{Array.isArray(record[key]) ? <ul className="organ-related-list">{(record[key] as unknown[]).map((item, index) => <li key={index}>{displayValue(item)}</li>)}</ul> : <p>{displayValue(record[key])}</p>}</section>)}<p className="organ-disclaimer">LifeLink provides operational coordination information. Final medical eligibility and allocation decisions remain with authorized professionals.</p></> : null}</main>;
}

function Metric({ icon, label, value, note }: { icon: React.ReactNode; label: string; value: number; note: string }) { return <article className="metric-card"><span className="metric-icon teal">{icon}</span><span className="eyebrow">{label}</span><strong>{value}</strong><small>{note}</small></article>; }
function OrganTable({ organs, onGenerateMatches }: { organs: Organ[]; onGenerateMatches?: (id: string) => void }) { return <div className="organ-table-wrap"><table className="organ-table"><thead><tr><th>Organ</th><th>Blood group</th><th>Status</th><th>Preservation timer</th><th>Donor reference</th><th>Location</th><th>Destination</th><th>Actions</th></tr></thead><tbody>{organs.map((organ) => <tr key={organ.id}><td><strong>{organ.reference}</strong><small>{organ.organType.replaceAll("_", " ")}</small></td><td>{organ.bloodGroup?.replaceAll("_", " +") ?? "—"}</td><td><span className={`pill ${organ.status.toLowerCase()}`}>{organ.status.replaceAll("_", " ").toLowerCase()}</span></td><td>{organ.preservation ? <PreservationClock remainingMs={Number(organ.preservation.remainingMs ?? 0)} status={String(organ.preservation.status ?? "NOT_STARTED")}/> : "Not started"}</td><td>{organ.donor?.reference ?? "Restricted"}</td><td>{organ.currentLocation?.name ?? "—"}</td><td>{organ.destinationCentre?.name ?? "—"}</td><td className="organ-row-actions"><Link className="text-button" href={`/organ-centre/organs/${organ.id}`}>View</Link>{organ.status === "AVAILABLE" && <button className="text-button" onClick={() => onGenerateMatches?.(organ.id)}>Find matches</button>}</td></tr>)}</tbody></table></div>; }
function CandidateTable({ matches, onShortlist, onOffer }: { matches: Row[]; onShortlist: (id: string) => void; onOffer: (id: string) => void }) { return <div className="organ-table-wrap"><table className="organ-table"><thead><tr><th>Recipient reference</th><th>Centre</th><th>Priority</th><th>Coordination score</th><th>Reasons</th><th>Review</th></tr></thead><tbody>{matches.map((match) => { const recipient = match.recipient as Row | undefined; return <tr key={String(match.id)}><td>{String(recipient?.reference ?? "—")}</td><td>{displayValue(recipient?.institution)}</td><td>{displayValue(recipient?.priority)}</td><td>{String(match.coordinationScore ?? "—")}</td><td>{Array.isArray(match.matchReasons) ? (match.matchReasons as string[]).join(" · ") : "—"}</td><td>{match.status === "SHORTLISTED" ? <button className="button small primary" onClick={() => onOffer(String(match.id))}>Create offer</button> : <button className="button small" onClick={() => onShortlist(String(match.id))}>Review and shortlist</button>}</td></tr>; })}</tbody></table></div>; }
function ResourceTable({ rows, resource, onOfferResponse, onAdvance }: { rows: Row[]; resource: Resource; onOfferResponse?: (id: string, action: "ACCEPT" | "REJECT") => void; onAdvance?: (id: string, status: string) => void }) {
	const fields: Record<Resource, string[]> = { organs: ["eventType", "fromStatus", "toStatus", "createdAt"], donors: ["reference", "donorType", "consentStatus", "authorizationStatus", "status", "createdAt"], recipients: ["reference", "organType", "bloodGroup", "priority", "status", "institution"], offers: ["reference", "organ", "recipient", "status", "responseDeadline", "receivingCentre"], procurements: ["organ", "status", "scheduledAt", "startedAt", "completedAt", "responsibleReference"], audit: ["eventType", "organ", "fromStatus", "toStatus", "createdAt"] };
	const detailBase: Partial<Record<Resource, string>> = { donors: "donors", recipients: "recipients", offers: "offers" };
	return <div className="organ-table-wrap"><table className="organ-table"><thead><tr>{fields[resource].map((field) => <th key={field}>{field.replaceAll(/([A-Z])/g, " $1")}</th>)}{["offers", "procurements"].includes(resource) && <th>Actions</th>}</tr></thead><tbody>{rows.map((row, index) => <tr key={String(row.id ?? index)}>{fields[resource].map((field) => <td key={field}>{field === "reference" && detailBase[resource] ? <Link className="text-button" href={`/organ-centre/${detailBase[resource]}/${String(row.id)}`}>{displayValue(row[field])}</Link> : displayValue(row[field])}</td>)}{resource === "offers" && <td>{["SENT", "UNDER_REVIEW"].includes(String(row.status)) ? <span className="offer-actions"><button className="button small" onClick={() => onOfferResponse?.(String(row.id), "ACCEPT")}>Accept</button><button className="button small danger" onClick={() => onOfferResponse?.(String(row.id), "REJECT")}>Reject</button></span> : "—"}</td>}{resource === "procurements" && <td>{row.status === "SCHEDULED" ? <button className="button small" onClick={() => onAdvance?.(String(row.id), "IN_PROGRESS")}>Start</button> : row.status === "IN_PROGRESS" ? <button className="button small primary" onClick={() => onAdvance?.(String(row.id), "COMPLETED")}>Mark retrieved</button> : "—"}</td>}</tr>)}</tbody></table></div>;
}
function nestedValue(row: Row, key: string) { const value = row[key]; if (value && typeof value === "object") return displayValue(value); return displayValue(value); }
function displayValue(value: unknown): string { if (value === null || value === undefined || value === "") return "—"; if (typeof value === "object") { const row = value as Row; return String(row.reference ?? row.name ?? row.organType ?? row.status ?? row.eventType ?? JSON.stringify(value)); } if (typeof value === "string" && value.includes("T")) return new Date(value).toLocaleString(); return String(value).replaceAll("_", " "); }

export function PreservationClock({ remainingMs: initialRemainingMs, status: initialStatus }: { remainingMs: number; status: string }) {
	const [remainingMs, setRemainingMs] = useState(initialRemainingMs); const [receivedAt] = useState(Date.now());
	useEffect(() => { const tick = () => setRemainingMs(Math.max(0, initialRemainingMs - (Date.now() - receivedAt))); tick(); const timer = window.setInterval(tick, 60_000); return () => window.clearInterval(timer); }, [initialRemainingMs, receivedAt]);
	const status = remainingMs <= 0 && initialStatus !== "NOT_STARTED" ? "EXPIRED" : initialStatus;
	if (status === "NOT_STARTED") return <span className="clock-state neutral">Not started</span>;
	const hours = Math.floor(remainingMs / 3_600_000); const minutes = Math.floor((remainingMs % 3_600_000) / 60_000);
	return <span className={`clock-state ${status.toLowerCase()}`}><strong>{String(hours).padStart(2,"0")}h {String(minutes).padStart(2,"0")}m</strong><small>{status.toLowerCase()} · operational timing</small></span>;
}
