"use client";
import dynamic from "next/dynamic";
import { useEffect,useState } from "react";
import { requestApi,ApiFailure } from "../../lib/api-client";

type Institution={id:string;name:string;type:string;address:string;latitude:number|null;longitude:number|null;distanceKm?:number};
const InstitutionMap=dynamic(()=>import("./leaflet-map"),{ssr:false,loading:()=> <div className="map-loading">Preparing institution map…</div>});
export default function InstitutionDiscovery(){const [institutions,setInstitutions]=useState<Institution[]>([]);const [type,setType]=useState("");const [radius,setRadius]=useState("50");const [coords,setCoords]=useState<{latitude:number;longitude:number}|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const search=async(position=coords)=>{setBusy(true);setError("");try{const params=new URLSearchParams();if(type)params.set("type",type);if(position){params.set("latitude",String(position.latitude));params.set("longitude",String(position.longitude));if(radius)params.set("radiusKm",radius);}const result=await requestApi<{institutions:Institution[]}>(`/api/institutions?${params}`);setInstitutions(result.institutions);}catch(e){setError(e instanceof ApiFailure?e.message:"Could not load institutions.");}finally{setBusy(false);}};
 useEffect(()=>{void search(null);},[]);const locate=()=>navigator.geolocation?.getCurrentPosition((p)=>{const position={latitude:p.coords.latitude,longitude:p.coords.longitude};setCoords(position);void search(position);},()=>setError("Location access was unavailable."));
 return <div className="page-stack"><header className="page-heading"><div><span className="eyebrow">LOCAL NETWORK</span><h1>Institution discovery</h1><p>Find active hospitals, blood banks, and organ centres near a location.</p></div></header><section className="panel map-filters"><label>Institution type<select value={type} onChange={(e)=>setType(e.target.value)}><option value="">All facilities</option><option value="HOSPITAL">Hospitals</option><option value="BLOOD_BANK">Blood banks</option><option value="ORGAN_CENTRE">Organ centres</option></select></label><label>Radius (km)<input type="number" min="1" max="500" value={radius} onChange={(e)=>setRadius(e.target.value)}/></label><button className="button quiet" onClick={locate}>Use my location</button><button className="button primary" onClick={()=>void search()} disabled={busy}>{busy?"Searching…":"Search map"}</button>{coords&&<span className="muted coordinates-hint">Location filter enabled</span>}</section>{error&&<p className="error">{error}</p>}<div className="map-results-layout"><section className="panel map-panel"><InstitutionMap institutions={institutions} center={coords?[coords.latitude,coords.longitude]:undefined}/></section><section className="panel facility-list"><div className="panel-heading"><div><span className="eyebrow">ACTIVE FACILITIES</span><h2>{institutions.length} found</h2></div></div>{institutions.length===0?<p className="empty">No active institutions match these filters.</p>:institutions.map((item)=><article className="facility-row" key={item.id}><span className="facility-dot">{item.type==="BLOOD_BANK"?"B":"H"}</span><div><strong>{item.name}</strong><p>{item.address||"Address not listed"}</p>{item.distanceKm!==undefined&&<small>{item.distanceKm.toFixed(1)} km away</small>}</div></article>)}</section></div><p className="map-disclaimer">Map pins show institution locations only. Inventory and ability to fulfil a request must be confirmed through the request workflow.</p></div>;
}
